print("Welcome! Calculate your BMI!")
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
result = weight/ (height*height)
result = round(result, 1)
print("Your BMI is: " + str(result))
